services:
#  user-service:
#    container_name: user-service-container
#    build:
#      context: .
#      dockerfile: ./services/user/Dockerfile
#    image: user-service
#    ports:
#      - ${USER_SERVICE_PORT}:8080
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
#      - SPRING_DATASOURCE_USERNAME=${USER_DB_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${USER_DB_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#    networks:
#      - task-management-application
#
#  task-service:
#    container_name: task-service-container
#    build:
#      context: .
#      dockerfile: ./services/task/Dockerfile
#    image: task-service
#    ports:
#      - ${TASK_SERVICE_PORT}:8081
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-db:5432/taskdb
#      - SPRING_DATASOURCE_USERNAME=${TASK_DB_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${TASK_DB_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_SHOW_SQL=true
#      - KAFKA_BROKER=kafka:9092
#    networks:
#      - task-management-application
#    depends_on:
#      - kafka
#
#  notification-service:
#    container_name: notification-service-container
#    build:
#      context: .
#      dockerfile: ./services/notification/Dockerfile
#    image: notification-service
#    ports:
#      - ${NOTIFICATION_SERVICE_PORT}:8082
#    environment:
#      - KAFKA_BROKER=kafka:9092
#    networks:
#      - task-management-application
#    depends_on:
#      - kafka

  user-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=${USER_DB_USERNAME}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
    ports:
      - ${USER_DB_PORT}:5433
    networks:
      - task-management-application

  task-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=${TASK_DB_USERNAME}
      - POSTGRES_PASSWORD=${TASK_DB_PASSWORD}
    ports:
      - ${TASK_DB_PORT}:5434
    networks:
      - task-management-application

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    networks:
      - task-management-application
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - task-management-application

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - task-management-application

networks:
  task-management-application:
    driver: bridge
