services:

  user-service:
    container_name: user-service-container
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    image: user-service
    ports:
      - 8080:8080
      - 5006:5006
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=${USER_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${USER_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    networks:
      - task-management-application

  task-service:
    container_name: task-service-container
    build:
      context: .
      dockerfile: ./services/task-service/Dockerfile
    image: task-service
    ports:
      - 8081:8081
      - 5005:5005
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=${TASK_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${TASK_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKER=kafka:9092
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    networks:
      - task-management-application
    depends_on:
      - kafka


  user-db:
    container_name: user-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=${USER_DB_USERNAME}
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
    ports:
      - 5433:5433
    networks:
      - task-management-application

  task-db:
    container_name: task-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=${TASK_DB_USERNAME}
      - POSTGRES_PASSWORD=${TASK_DB_PASSWORD}
    ports:
      - 5434:5434
    networks:
      - task-management-application

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5050:80
    networks:
      - task-management-application


  notification-service:
    container_name: notification-service-container
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    image: notification-service
    ports:
      - 8082:8082
      - 5007:5007
    environment:
      - KAFKA_BROKER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=${TASK_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${TASK_DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - task-management-application
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    networks:
      - task-management-application
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - task-management-application


  api-gateway:
    container_name: api-gateway-container
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    image: api-gateway
    ports:
      - 8084:8084
      - 5008:5008
    networks:
      - task-management-application


networks:
  task-management-application:
    driver: bridge
